framework:
  asset_mapper:
    # The paths to make available to the asset mapper.
    paths:
      - assets/
      - vendor/twbs/bootstrap/
    excluded_patterns:
      - "*/assets/styles/_*.scss"
      - "*/assets/styles/**/_*.scss"
sensiolabs_typescript:
  source_dir:
    - "%kernel.project_dir%/assets/app"
    - "%kernel.project_dir%/assets/controllers"
