meilisearch:
  url: "%env(MEILISEARCH_URL)%" # URL of the Meilisearch server (mandatory)
  api_key: "%env(MEILISEARCH_API_KEY)%" # API key to access the Meilisearch server (mandatory)
  indices:
    - name: questions
      class: App\Entity\Question
      enable_serializer_groups: true
      settings:
        filterableAttributes:
          - type
          - difficulty
        sortableAttributes:
          - id

when@preprod:
  meilisearch:
    prefix: prod_
