framework:
  notifier:
    chatter_transports:
      linenotify: "%env(LINE_NOTIFY_DSN)%"
    texter_transports:
    channel_policy:
      urgent: ["chat/linenotify"]
      high: ["chat/linenotify"]
      medium: ["chat/linenotify"]
      low: ["chat/linenotify"]
    admin_recipients:
      - { email: dbplay@pan93.com }
