twig:
  file_name_pattern: "*.twig"
  form_themes: ["bootstrap_5_layout.html.twig"]
  globals:
    umami_domain: "%env(UMAMI_DOMAIN)%"
    umami_website_id: "%env(UMAMI_WEBSITE_ID)%"
    appfeatures:
      hint: "%app.features.hint%"
      comment: "%app.features.comment%"

when@test:
  twig:
    strict_variables: true
